/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WidgetsRouteImport } from './routes/widgets'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as PedirAvaliacaoRouteImport } from './routes/pedir-avaliacao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosNovoRouteImport } from './routes/projetos_.novo'
import { Route as EmbedSlugRouteImport } from './routes/embed.$slug'
import { Route as ColetarSlugRouteImport } from './routes/coletar.$slug'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ProjetosIdEditarRouteImport } from './routes/projetos_.$id.editar'
import { Route as ApiVideosIdRouteImport } from './routes/api/videos.$id'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe.webhook'
import { Route as ApiLogosIdRouteImport } from './routes/api/logos.$id'

const WidgetsRoute = WidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const PedirAvaliacaoRoute = PedirAvaliacaoRouteImport.update({
  id: '/pedir-avaliacao',
  path: '/pedir-avaliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosNovoRoute = ProjetosNovoRouteImport.update({
  id: '/projetos_/novo',
  path: '/projetos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedSlugRoute = EmbedSlugRouteImport.update({
  id: '/embed/$slug',
  path: '/embed/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ColetarSlugRoute = ColetarSlugRouteImport.update({
  id: '/coletar/$slug',
  path: '/coletar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIdEditarRoute = ProjetosIdEditarRouteImport.update({
  id: '/projetos_/$id/editar',
  path: '/projetos/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideosIdRoute = ApiVideosIdRouteImport.update({
  id: '/api/videos/$id',
  path: '/api/videos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogosIdRoute = ApiLogosIdRouteImport.update({
  id: '/api/logos/$id',
  path: '/api/logos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pedir-avaliacao': typeof PedirAvaliacaoRoute
  '/projetos': typeof ProjetosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/widgets': typeof WidgetsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/c/$token': typeof CTokenRoute
  '/coletar/$slug': typeof ColetarSlugRoute
  '/embed/$slug': typeof EmbedSlugRoute
  '/projetos/novo': typeof ProjetosNovoRoute
  '/api/logos/$id': typeof ApiLogosIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/videos/$id': typeof ApiVideosIdRoute
  '/projetos/$id/editar': typeof ProjetosIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pedir-avaliacao': typeof PedirAvaliacaoRoute
  '/projetos': typeof ProjetosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/widgets': typeof WidgetsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/c/$token': typeof CTokenRoute
  '/coletar/$slug': typeof ColetarSlugRoute
  '/embed/$slug': typeof EmbedSlugRoute
  '/projetos/novo': typeof ProjetosNovoRoute
  '/api/logos/$id': typeof ApiLogosIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/videos/$id': typeof ApiVideosIdRoute
  '/projetos/$id/editar': typeof ProjetosIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pedir-avaliacao': typeof PedirAvaliacaoRoute
  '/projetos': typeof ProjetosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/widgets': typeof WidgetsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/c/$token': typeof CTokenRoute
  '/coletar/$slug': typeof ColetarSlugRoute
  '/embed/$slug': typeof EmbedSlugRoute
  '/projetos_/novo': typeof ProjetosNovoRoute
  '/api/logos/$id': typeof ApiLogosIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/videos/$id': typeof ApiVideosIdRoute
  '/projetos_/$id/editar': typeof ProjetosIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/cadastro'
    | '/configuracoes'
    | '/dashboard'
    | '/login'
    | '/pedir-avaliacao'
    | '/projetos'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/widgets'
    | '/auth/callback'
    | '/c/$token'
    | '/coletar/$slug'
    | '/embed/$slug'
    | '/projetos/novo'
    | '/api/logos/$id'
    | '/api/stripe/webhook'
    | '/api/videos/$id'
    | '/projetos/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/cadastro'
    | '/configuracoes'
    | '/dashboard'
    | '/login'
    | '/pedir-avaliacao'
    | '/projetos'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/widgets'
    | '/auth/callback'
    | '/c/$token'
    | '/coletar/$slug'
    | '/embed/$slug'
    | '/projetos/novo'
    | '/api/logos/$id'
    | '/api/stripe/webhook'
    | '/api/videos/$id'
    | '/projetos/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/cadastro'
    | '/configuracoes'
    | '/dashboard'
    | '/login'
    | '/pedir-avaliacao'
    | '/projetos'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/widgets'
    | '/auth/callback'
    | '/c/$token'
    | '/coletar/$slug'
    | '/embed/$slug'
    | '/projetos_/novo'
    | '/api/logos/$id'
    | '/api/stripe/webhook'
    | '/api/videos/$id'
    | '/projetos_/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  CadastroRoute: typeof CadastroRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PedirAvaliacaoRoute: typeof PedirAvaliacaoRoute
  ProjetosRoute: typeof ProjetosRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  WidgetsRoute: typeof WidgetsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CTokenRoute: typeof CTokenRoute
  ColetarSlugRoute: typeof ColetarSlugRoute
  EmbedSlugRoute: typeof EmbedSlugRoute
  ProjetosNovoRoute: typeof ProjetosNovoRoute
  ApiLogosIdRoute: typeof ApiLogosIdRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiVideosIdRoute: typeof ApiVideosIdRoute
  ProjetosIdEditarRoute: typeof ProjetosIdEditarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widgets': {
      id: '/widgets'
      path: '/widgets'
      fullPath: '/widgets'
      preLoaderRoute: typeof WidgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedir-avaliacao': {
      id: '/pedir-avaliacao'
      path: '/pedir-avaliacao'
      fullPath: '/pedir-avaliacao'
      preLoaderRoute: typeof PedirAvaliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos_/novo': {
      id: '/projetos_/novo'
      path: '/projetos/novo'
      fullPath: '/projetos/novo'
      preLoaderRoute: typeof ProjetosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$slug': {
      id: '/embed/$slug'
      path: '/embed/$slug'
      fullPath: '/embed/$slug'
      preLoaderRoute: typeof EmbedSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coletar/$slug': {
      id: '/coletar/$slug'
      path: '/coletar/$slug'
      fullPath: '/coletar/$slug'
      preLoaderRoute: typeof ColetarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos_/$id/editar': {
      id: '/projetos_/$id/editar'
      path: '/projetos/$id/editar'
      fullPath: '/projetos/$id/editar'
      preLoaderRoute: typeof ProjetosIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/videos/$id': {
      id: '/api/videos/$id'
      path: '/api/videos/$id'
      fullPath: '/api/videos/$id'
      preLoaderRoute: typeof ApiVideosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logos/$id': {
      id: '/api/logos/$id'
      path: '/api/logos/$id'
      fullPath: '/api/logos/$id'
      preLoaderRoute: typeof ApiLogosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  CadastroRoute: CadastroRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PedirAvaliacaoRoute: PedirAvaliacaoRoute,
  ProjetosRoute: ProjetosRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  WidgetsRoute: WidgetsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CTokenRoute: CTokenRoute,
  ColetarSlugRoute: ColetarSlugRoute,
  EmbedSlugRoute: EmbedSlugRoute,
  ProjetosNovoRoute: ProjetosNovoRoute,
  ApiLogosIdRoute: ApiLogosIdRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiVideosIdRoute: ApiVideosIdRoute,
  ProjetosIdEditarRoute: ProjetosIdEditarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
